permalink: /:year/:month/:day/:title.html
url: "http://g33kfun.github.io"
full_name: "Geek Fun"
first_name: "Geek"
last_name: "Stuff"
blog_title: "Geeky Stuff"
author_img_name_path: ""
disqus_shortname: ""
copyright_year: "2015"
google_analytics_code: #"UA-63994692-1"
aboutme: "All about Geeky Stuff, Fun & Images"
